version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      MYSQL_HOST: 10.0.248.15
      MYSQL_DATABASE: bible_verses
      MYSQL_USER: sqlsevr
      MYSQL_PASSWORD: Gamma99Quest
